### PR TITLE
feat(RDGRS-752): Chisel update

### PR DESCRIPTION
**Pull request by NewtonMan**
### Jira Issue
[RDGRS-752](https://outsystemsrd.atlassian.net/browse/RDGRS-752)

[RDGRS-752]: https://outsystemsrd.atlassian.net/browse/RDGRS-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by NewtonMan** [comment]
Screenshot 2024-10-17 at 10 50 21

**Comment by NewtonMan** [comment]
I will provide more evidences that its ok then I request the review

**Comment by NewtonMan** [comment]
Screenshot 2024-12-02 at 17 04 10

**Review by bmartins-unit — APPROVED** [review]

**Comment by NewtonMan** [comment]
Screenshot 2024-12-03 at 10 27 58
Screenshot 2024-12-03 at 10 34 34
Screenshot 2024-12-03 at 10 34 08
Screenshot 2024-12-03 at 10 33 46
Screenshot 2024-12-03 at 10 31 39
Screenshot 2024-12-03 at 10 31 13
Screenshot 2024-12-03 at 10 28 48
Screenshot 2024-12-03 at 10 28 06

**Pull request merged**
